CREATE TYPE "public"."ai_job_status" AS ENUM('queued', 'running', 'succeeded', 'failed', 'needs_human');--> statement-breakpoint
CREATE TYPE "public"."ai_job_type" AS ENUM('extraction', 'explanation', 'ingest');--> statement-breakpoint
CREATE TABLE "ai_jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"type" "ai_job_type" NOT NULL,
	"status" "ai_job_status" DEFAULT 'queued' NOT NULL,
	"subject_type" varchar(60),
	"subject_id" varchar(80),
	"requested_by" uuid,
	"correlation_id" varchar(64),
	"provider" varchar(40),
	"model" varchar(80),
	"prompt_version" varchar(40),
	"input" jsonb,
	"output" jsonb,
	"tokens_in" integer,
	"tokens_out" integer,
	"cost_usd" numeric(10, 6),
	"latency_ms" integer,
	"error" text,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"actor_id" uuid,
	"actor_role" "role_name",
	"action" varchar(80) NOT NULL,
	"entity_type" varchar(60) NOT NULL,
	"entity_id" varchar(80) NOT NULL,
	"before" jsonb,
	"after" jsonb,
	"ip" varchar(64),
	"correlation_id" varchar(64),
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refresh_tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"family_id" uuid NOT NULL,
	"token_hash" varchar(64) NOT NULL,
	"issued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoked_reason" varchar(40),
	"replaced_by_id" uuid,
	"user_agent" varchar(200),
	"ip" varchar(64),
	CONSTRAINT "refresh_tokens_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
ALTER TABLE "ai_jobs" ADD CONSTRAINT "ai_jobs_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_jobs" ADD CONSTRAINT "ai_jobs_requested_by_users_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_replaced_by_id_refresh_tokens_id_fk" FOREIGN KEY ("replaced_by_id") REFERENCES "public"."refresh_tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ai_jobs_org_id_created_at_idx" ON "ai_jobs" USING btree ("org_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ai_jobs_status_idx" ON "ai_jobs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ai_jobs_type_status_idx" ON "ai_jobs" USING btree ("type","status");--> statement-breakpoint
CREATE INDEX "ai_jobs_subject_idx" ON "ai_jobs" USING btree ("subject_type","subject_id");--> statement-breakpoint
CREATE INDEX "audit_log_org_id_at_idx" ON "audit_log" USING btree ("org_id","at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_log_entity_idx" ON "audit_log" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "audit_log_actor_id_idx" ON "audit_log" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "refresh_tokens_family_id_idx" ON "refresh_tokens" USING btree ("family_id");--> statement-breakpoint
--
-- HAND-WRITTEN, not generated by drizzle-kit. Drizzle's schema DSL cannot
-- express Postgres rules, so re-running `db:generate` will not reproduce these
-- three statements — if this migration is ever regenerated, they must be
-- carried across by hand.
--
-- DESIGN.md §8 (Repudiation) requires that "decisions are never updated in
-- place". A convention cannot deliver that; an ORM helper cannot either, since
-- anything that can write can also rewrite. A rule can: the rewriter turns the
-- statement into nothing at all, for every role including the table owner and a
-- superuser, and it applies to code that never heard of AuditService.
--
-- DO INSTEAD NOTHING is deliberately silent rather than an exception. An
-- attempted rewrite reports "0 rows affected" and continues. The alternative —
-- a trigger that RAISEs — turns a stray `updated_at` bump somewhere in a later
-- phase into a 500 on a request that had otherwise succeeded, which trades a
-- data-integrity guarantee for an availability bug.
--
-- Consequence worth knowing: rules do not apply to TRUNCATE. Clearing this
-- table for a reseed or between test cases is therefore `TRUNCATE audit_log`,
-- and that is the only sanctioned way to empty it. See scripts/seed.ts.
--
CREATE RULE audit_log_no_update AS ON UPDATE TO audit_log DO INSTEAD NOTHING;--> statement-breakpoint
CREATE RULE audit_log_no_delete AS ON DELETE TO audit_log DO INSTEAD NOTHING;
